
#ifndef TIPO_DE_TOKEN_H
#define TIPO_DE_TOKEN_H

enum class TipoDeToken {
    IDENTIFICADOR,
    NUMERO_INTEIRO,
    OPERADOR_ARITMETICO,
    OPERADOR_RELACIONAL,
    OPERADOR_LOGICO,
    ATRIBUICAO,
    PARENTESE_ESQ,
    PARENTESE_DIR,
    CHAVE_ESQ,
    CHAVE_DIR,
    PONTO_VIRGULA,
    VIRGULA,
    PALAVRA_CHAVE,
    INVALIDO,
    FIM
};

#endif
