#ifndef TIPODETOKEN_H
#define TIPODETOKEN_H

enum class TipoDeToken {
    NUMERO_INTEIRO,
    NUMERO_REAL,
    IDENTIFICADOR,
    PALAVRA_RESERVADA,
    OPERADOR_ARITMETICO,
    OPERADOR_ATRIBUICAO,
    PONTO_E_VIRGULA,
    OPERADOR_RELACIONAL,
    OPERADOR_LOGICO,
    ABRE_PARENTESES,
    FECHA_PARENTESES,
    ABRE_CHAVES,
    FECHA_CHAVES,
    ABRE_COLCHETES,
    FECHA_COLCHETES,
    VIRGULA,
    STRING,
    PONTO,
    DOIS_PONTOS,
    INTERROGACAO,
    INCREMENTO,
    DECREMENTO,
    ABRE_ASPAS,
    FECHA_ASPAS,
    TOKEN_INVALIDO
};

#endif // TIPODETOKEN_H
